import bookMenu from './book-menu.js';
import contact from './contact.js';
import coverLazyLoading from './cover-lazy-loading.js';
import externalLinks from './external-links.js';
import lazyLoading from './lazy-loading.js';
import offline from './offline.js';
import randomization from './randomization.js';
import serviceWorker from './service-worker.js';
import stickyElements from './sticky-elements.js';
import viewer from './viewer.js';

bookMenu();
contact();
coverLazyLoading();
externalLinks();
lazyLoading();
offline();
randomization(() => coverLazyLoading());
serviceWorker();
stickyElements();
viewer();
